-- LEGACY MIGRATION - DO NOT APPLY TO THE LIVE SDC DATABASE.
--
-- The live Cloud SQL database already contains integer-ID versions of:
-- batches, batch_streams, batch_subjects, students, parents, auth,
-- student_batches, student_parents, announcements, lectures,
-- study_materials, and pyq_papers.
--
-- An older version of this file attempted to create UUID-based replacements
-- with incompatible columns. It has intentionally been made a no-op so it
-- cannot damage or diverge the live schema.
--
-- Before adding future migrations, capture the live schema with:
--   pg_dump --schema-only --no-owner --no-privileges sdc_database
