-- Additive teacher model for the existing integer-ID SDC schema.
-- Review and apply to sdc_database before enabling teacher creation.
-- This migration does not change the auth.role constraint.

BEGIN;

CREATE TABLE IF NOT EXISTS teachers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id integer UNIQUE REFERENCES auth(id) ON DELETE SET NULL,
  name varchar NOT NULL,
  phone varchar UNIQUE,
  email varchar UNIQUE,
  experience varchar,
  status varchar NOT NULL DEFAULT 'Active'
    CHECK (status IN ('Active', 'Inactive', 'On Leave')),
  created_by integer REFERENCES auth(id) ON DELETE SET NULL,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS teacher_subjects (
  teacher_id integer NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  subject varchar NOT NULL,
  PRIMARY KEY (teacher_id, subject)
);

CREATE TABLE IF NOT EXISTS teacher_batch_assignments (
  batch_id integer NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
  teacher_id integer NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  assigned_by integer REFERENCES auth(id) ON DELETE SET NULL,
  assigned_at timestamp without time zone NOT NULL DEFAULT NOW(),
  PRIMARY KEY (batch_id, teacher_id)
);

CREATE INDEX IF NOT EXISTS idx_teacher_batch_assignments_teacher
  ON teacher_batch_assignments (teacher_id);

CREATE INDEX IF NOT EXISTS idx_teacher_subjects_subject
  ON teacher_subjects (subject);

COMMIT;
