-- Additive operational tables for attendance, tests/results, homework,
-- fees, and doubts. Apply only after 002_teachers.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS attendance_sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lecture_id integer UNIQUE REFERENCES lectures(id) ON DELETE SET NULL,
  batch_id integer NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
  subject varchar NOT NULL,
  session_date date NOT NULL,
  created_by integer REFERENCES auth(id) ON DELETE SET NULL,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  UNIQUE (batch_id, subject, session_date, lecture_id)
);

CREATE TABLE IF NOT EXISTS attendance_records (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id integer NOT NULL REFERENCES attendance_sessions(id) ON DELETE CASCADE,
  student_auth_id integer NOT NULL REFERENCES auth(id) ON DELETE CASCADE,
  status varchar NOT NULL CHECK (status IN ('present', 'absent', 'late', 'excused')),
  marked_by integer REFERENCES auth(id) ON DELETE SET NULL,
  marked_at timestamp without time zone NOT NULL DEFAULT NOW(),
  UNIQUE (session_id, student_auth_id)
);

CREATE TABLE IF NOT EXISTS tests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id integer NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
  title varchar NOT NULL,
  subject varchar NOT NULL,
  scheduled_at timestamp with time zone NOT NULL,
  duration_mins integer NOT NULL CHECK (duration_mins > 0),
  total_marks numeric(8, 2) NOT NULL CHECK (total_marks > 0),
  status varchar NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'scheduled', 'completed', 'published', 'cancelled')),
  created_by integer REFERENCES auth(id) ON DELETE SET NULL,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS test_results (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id integer NOT NULL REFERENCES tests(id) ON DELETE CASCADE,
  student_auth_id integer NOT NULL REFERENCES auth(id) ON DELETE CASCADE,
  marks numeric(8, 2) NOT NULL CHECK (marks >= 0),
  rank integer CHECK (rank > 0),
  remarks text,
  published_at timestamp without time zone,
  UNIQUE (test_id, student_auth_id)
);

CREATE TABLE IF NOT EXISTS homework (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id integer NOT NULL REFERENCES batches(id) ON DELETE CASCADE,
  title varchar NOT NULL,
  subject varchar NOT NULL,
  description text,
  due_at timestamp with time zone NOT NULL,
  created_by integer REFERENCES auth(id) ON DELETE SET NULL,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS homework_submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  homework_id integer NOT NULL REFERENCES homework(id) ON DELETE CASCADE,
  student_auth_id integer NOT NULL REFERENCES auth(id) ON DELETE CASCADE,
  status varchar NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'submitted', 'reviewed', 'late')),
  submission_url text,
  submitted_at timestamp with time zone,
  score numeric(8, 2),
  feedback text,
  UNIQUE (homework_id, student_auth_id)
);

CREATE TABLE IF NOT EXISTS fee_invoices (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_auth_id integer NOT NULL REFERENCES auth(id) ON DELETE CASCADE,
  description varchar NOT NULL,
  amount numeric(12, 2) NOT NULL CHECK (amount >= 0),
  amount_paid numeric(12, 2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  due_date date NOT NULL,
  status varchar NOT NULL DEFAULT 'due'
    CHECK (status IN ('due', 'partially_paid', 'paid', 'overdue', 'cancelled')),
  payment_reference varchar,
  created_by integer REFERENCES auth(id) ON DELETE SET NULL,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW(),
  CHECK (amount_paid <= amount)
);

CREATE TABLE IF NOT EXISTS doubts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_auth_id integer NOT NULL REFERENCES auth(id) ON DELETE CASCADE,
  batch_id integer REFERENCES batches(id) ON DELETE SET NULL,
  subject varchar NOT NULL,
  title varchar NOT NULL,
  description text NOT NULL,
  status varchar NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'assigned', 'answered', 'closed')),
  assigned_teacher_id integer REFERENCES teachers(id) ON DELETE SET NULL,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS doubt_messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doubt_id integer NOT NULL REFERENCES doubts(id) ON DELETE CASCADE,
  sender_auth_id integer NOT NULL REFERENCES auth(id) ON DELETE CASCADE,
  message text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_attendance_records_student ON attendance_records (student_auth_id);
CREATE INDEX IF NOT EXISTS idx_tests_batch_schedule ON tests (batch_id, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_test_results_student ON test_results (student_auth_id);
CREATE INDEX IF NOT EXISTS idx_homework_batch_due ON homework (batch_id, due_at);
CREATE INDEX IF NOT EXISTS idx_homework_submissions_student ON homework_submissions (student_auth_id);
CREATE INDEX IF NOT EXISTS idx_fee_invoices_student_status ON fee_invoices (student_auth_id, status);
CREATE INDEX IF NOT EXISTS idx_doubts_student_status ON doubts (student_auth_id, status);

COMMIT;
